#%RAML 1.0 Trait
queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [sami, geb]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: sami