#%RAML 1.0 Library
usage: to define  basic library which are used on this rest api raml specification
types:
    catagory: !include Datatypes/catagory.raml
    catagoryid: !include Datatypes/catagoryid.raml
    order: !include Datatypes/order.raml
    orderid: !include Datatypes/orderid.raml
    orderuid: !include Datatypes/orderuid.raml
    product: !include Datatypes/product.raml
    productid: !include Datatypes/productid.raml
    user: !include Datatypes/user.raml
    userid: !include Datatypes/userid.raml
    uid: !include Datatypes/uid.raml
traits:
  respomessage: !include traites/errorTrait.raml

annotationTypes:
  annotation: !include annotation.raml

securitySchemes:
  security:  !include  secureschema/securityScheme.raml
resourceTypes:
  collection: !include resource/Collection.raml
  getCollection: !include resource/getCollection.raml
  
  catagories: !include resource/catagories.raml
  catagoryid: !include resource/catagoryid.raml
  orders: !include  resource/orders.raml
  orderid: !include  resource/orderid.raml
  orderuid: !include  resource/orderuid.raml
  product: !include  resource/product.raml
  productid: !include  resource/productid.raml
  users: !include resource/users.raml
  userid: !include  resource/userid.raml









 