#%RAML 1.0 NamedExample
OrderResponsePost:
                addressid: 3589068800000,
                amount: 86,
                created: 1589068800000,
                discountid: 300,
                modified: 1589068800000,
                orderid: 125,
                status: ok,
                userid: 322