#%RAML 1.0 NamedExample
OrderRequestPost:
                addressid: 15890680,
                amount: 156,
                created: 158906880,
                discountid: 000,
                modified: 15890600,
                orderid: 13,
                status: ok,
                userid: 224