#%RAML 1.0 Library
usage:

traits:
  OnlineShopTraits: !include trait/response.raml
resourceTypes:
  rootcollection: !include resource/rootresourceType.raml
  adminServ: !include resource/adminresourceType.raml
securitySchemes:
  oauth2-schema: !include exchange_modules/4ec08928-d376-44af-81e6-5233186f427a/oauth20/1.0.1/oauth2.0.raml

annotationTypes:
  annotation: !include annotation.raml




  