#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: This Api support 2.0 security
describedBy:
  headers:
    Authorization: 
      description: User have to send token to access any resource 
      type: string
  responses:
    401:
      body:
        application/json:
          example:
            {
              message: "bad  or expired token is used"
            }
    403:
      body:
        application/json:
          example:
            {
              message: "not allowed to use resource"
            }

  