#%RAML 1.0 Trait
responses:
  200:
    body:
      application/json:
        example:
          {
            "userid": 900,
            "email": "abcdkkk@gmail.com",
            "date_joined": -1573012800000,
            "modified": 1582747201000,
            "type": 1,
            "deleted": false,
            "username": "Abc"
          }
  401:
    body:
      application/json:
        example:
          {
            "message": "Unauthorized Person"
          }
    


  403:
    body:
      application/json:
          example:
            {
                "message": "Forbidden"
            }
