#%RAML 1.0 Trait
responses:
  200:
        body:
          application/json:
            example:
              {"uid": 900} 
  201:
        body:
          application/json:
            example:
              {
                "Message": "Account Created"
              }
  401:
        body:
          application/json:
            example:
              {
                "message": "Unauthorized Person"
              }
  
  403:
        body:
          application/json:
            example:
              {
                "message": "Forbidden"
              }
  
  404:
        body:
          application/json:
            example:
              {
                "message": "Sorry,Page Not Found"
              }