#%RAML 1.0 Extension
extends: craft-online-shopping.raml
resourceTypes:
  collection: !include  Resource/AdminresourceType.raml
/Adminusers:
  # get:
  #   responses:
  #     404:
  #       body:
  #         application/json:
  #           example:
  #             {
  #               "message":"user not found"
  #             }
  type:
    collection:
      resourcePathName: product
      resourcePath: product 
  
  delete:    
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":" deleted"
              } 


          
/user/{ID}:
  get:
  post:
  put:
  delete:    
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"message deleted"
              }                        

/Adminproducts:
  # get:
  #   responses:
  #     404:
  #       body:
  #         application/json:
  #           example:
  #             {
  #               "message":"product not found"
  #             }
  type:
    collection:
      resourcePathName: product
      resourcePath: product            

  post:
  put:
  delete:    
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"resource deleted"
              } 


/product/{ID}:
  get:
  post:
  put:
  delete:    
    responses:
      200:
        body:
          application/json:
            example: 
              {
                "message":"resource deleted"
              } 


/Adminorders:
  get:
    responses:
      404:
        body:
          application/json:
            example:
              {
                "message":" order not found"
              }
  post:
  put:
  # delete:    
  #   responses:
  #     200:
  #       body:
  #         application/json:
  #           example:
  #             {
  #               "message":"order deleted"
  #             }  
  type:
    collection:
      resourcePathName: product
      resourcePath: product            

 
/order/{uid}:
  get:
  post:
  put:
  delete:    
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"message deleted"
              }  


  

/catagories:
  get:
    responses:
      404:
        body:
          application/json:
            example:
              {
                "message":catagory not found"
              }
          
  post:
  put:
  # delete:    
  #   responses:
  #     200:
  #       body:
  #         application/json:
  #           example:
  #             {
  #               "message":"resource deleted"
  #             }  
  type:
    collection:
      resourcePathName: product
      resourcePath: product            

/catagory/{ID}:
  get:
  post:
  put:
  delete:    
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message":"resource deleted"
              }  

 













