#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/f3c02441-13a3-46c9-afe6-95accdfa597a/ # 
title: Craft online shopping
version: 1.0
mediaType: 
- application/json

protocols:
  - http  



uses:
  lib: library.raml 
/users:
  description: this the users resource
  get:
    queryParameters:
      Id:
        description: id
        type: integer
        required: false
      fullname:
        description: fname and lname
        type: string
        enum:
          [john,mike]
        required: false 
      username:
        description: username
        maxLength: 10
        minLength: 2
        required: false
        default: john
   
 
    description: usrs resource get http method response
    responses:
      200:
        body:
          application/json:
        
            example: !include Examples/users.raml    
  # type:
  #   collection:
  #     resourcePath: lib.user

  is:
    lib.respoMessage:
      

          
/user/{ID}:
  description: this is ther users resource
  get:
    responses:
      200:
        body:
          application/json:
            example: !include Examples/usersID.raml
  # type:
  #   collection:
  #     resourcePath: users
    is:
     lib.respoMessage: 

  post:
    description: list of post status code
    responses:
      200:
        body:
          application/json:
            example: !include Examples/usersPost.raml

      201:
        body:
          application/json:
            example:
              {
                "message":"created"
              }

  is:
    lib.respoMessage:
    

/products:
  get:
    description: find product resources
    responses:
      200:
        body:
          application/json:
            example: !include Examples/products.raml
  # type:
  #   collection:
  #     resourcePath: users

  is:
    lib.respoMessage:

/product/{ID}:
  get:
    description: get all products
    responses:
      200:
        body:
          application/json:
            examples: !include Examples/productsID.raml

  is:
    lib.respoMessage:

/orders:
  description:
  get: 
   responses: 
    200:
      body:
        application/json:
          example: !include Examples/orders.raml
  is:
    lib.respoMessage:

/order/{uid}:
  description: get order by id
  get:
    responses:
      200:
        body:
          application/json:
            example: !include Examples/orderID.raml

  # type:
  #   collection:
  #     resourcePath: users

  is:
    lib.respoMessage:

/orders getallorders: 
  description: get all orders
  get:
    responses:
      200:
        body:
          application/json:
            example: !include Examples/ordersgetall.raml

  is:
    lib.respoMessage:

  post:
    responses:
      200:
        body:
          application/json:
            example: !include Examples/orderspost.raml
              

      201:
        body:
          application/json:
            example:
              {
                "message":"created"
              }

/catagories:
  description: 
  get:
    responses:
      200:
        body:
          application/json:
            example: !include Examples/Catagories.raml

  is:
    lib.respoMessage:

/catagory/{ID}:
  description: 
  get:
    responses:
      200:
        body:
          application/json:
            example: !include Examples/catagory.raml

  # type:
  #   collection:
  #     resourcePath: users

  is:
    lib.respoMessage:                    




















              

                                         