#%RAML 1.0 Library
usage: To define basic lib which are used on this rest api raml specification.
types:
  users: !include Datatypes/UsersdataType.raml
  product: !include Datatypes/productsdataType.raml
  orders: !include Datatypes/ordersdataType.raml
  catagory: !include Datatypes/CatagorydataType.raml
traits:
  respoMessage: !include Traits/responses.raml
securitySchemes:
  Basic auth: !include securityScheme.raml
# documentation: 
#  - !include documentation.raml
resourceTypes:
  collection: !include Resource/rootresourceType.raml
annotationTypes:
  annotation: !include annotation.raml 