#%RAML 1.0 SecurityScheme
type: Basic Authentication
description: This Api support basic auth security
describedBy:
  headers:
    Authorization:
      description: user have to send correct password to access any resource
      type: string 
  responses:
    401:
      body:
        application/json:
          example:
            {
              "message":"incorrect password"
            }
    403:
      description: not allowed to access the resource

               