#%RAML 1.0 ResourceType
get:
    responses:
      404:
        body:
          application/json:
            example:
              {
                "message" : "<<resourcePathName>> not found"
              } 
