#%RAML 1.0 ResourceType
get:
    responses:
      501:
        body:
          application/json:
            example:
              {
                "message" : "<<resourcePathName>> server failed for response"
              } 
