#%RAML 1.0 ResourceType
post: 
  description: the new resource <<resourcePathName>> is not found
  responses:
     200:
       body:
         application/json:
           example:             
               {
                    "<<resourcePath>> is recorded seccessfully"
                                }