#%RAML 1.0 ResourceType
description: the resource <<resourcePathName>> is updated successfully
put:
    description: update an existing record in the list
    responses:
      200:
        body:
          application/json:
            example:
              
             {
              messege: "<<resourcePath>> is updated seccessfully"
              
            }