#%RAML 1.0 Extension
extends: online-shoppiing.raml
resourceTypes:
  collection: !include resource/AdminResource.raml
  
/Adminproduct:
  type:
    collection:
      resourcePathName: product
  
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": "resource deleted"
              }  
/Adminusers:
  type:
    collection:
      resourcePathName: user


  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": "resource deleted"
              }

/Adminorders:
  type:
    collection:
      resourcePathName: order

  post:
  put:
  delete:

    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": "resource deleted"
              }














