#%RAML 1.0 NamedExample
categoryExample:
  [ {
                  "categoryid": 10,
                  "name": "labtop"
              },
          
              {
                "categoryid": 11,
                 "name": "laptops"
              }
              ]