#%RAML 1.0 NamedExample
productsIdExample:
  {
                "productid": 200,
                "categoryid": 10,
                "name": "mobilemp",
                "description": "dderesrt",
                "video_url": "sss@vv.mail",
                "price": 1.0E8
              }