#%RAML 1.0 NamedExample
{
                "orderid": 1333,
                "userid": 1302,
                "addressid": 201,
                "discountid": 1,
                "created": "2020-11-06",
                "modified": "2020-11-10",
                "status": "Accepted",
                "amount": 1000
              }
