#%RAML 1.0 ResourceType
 get:
  description: uthe resource  <<resourcePathName>> not found
  responses:
     501:
        body:
          application/json:
            example:
              {
                "Message": "<<resourcePath>> server failed for responce"
              }