#%RAML 1.0 DocumentationItem
title: online shoppinguser documentation overview
content: This Rest Apicontain four major Resourses user, order, product, catagory. under each resourse we may have four different kinds of HTTp Method. That are Get, Post, Put and Delete