#%RAML 1.0 DataType
type: object
properties:
     orderid: integer
     email: string
     date_joined: date-only
     modified: integer
     type: integer
     deleted: boolean
     username: string
#   "orderid": 1464,
#      "email": "betty123@gmail",
#      "date_joined": 1796297152000,
#      "modified": 1696297152000,
#      "type": 1,
#      "deleted": false,
#      "username": "ab12324"