#%RAML 1.0 DataType
type: object
properties:
  productid: integer
  categoryid: integer
  name: string
  description: string
  video: string
  price: integer

# {
#       "productid": 0,
#       "categoryid": 10,
#       "name": "FZA",
#       "description": "NEHA",
#       "video_url": "www.craft.com",
#       "price": 4414
#    }