#%RAML 1.0 NamedExample
[
  {
                "orderid": 1333,
                "userid": 1302,
                "addressid": 201,
                "discountid": 1,
                "created": "string",
                "modified": "string",
                "status": "Accepted",
                "amount": 1000
              },
              {
                "orderid": 1335,
                "userid": 1302,
                "addressid": 201,
                "discountid": 1,
                "created": "string",
                "modified": "string",
                "status": "Accepted",
                "amount": 1000
              }
              ]      