#%RAML 1.0 Trait
responses:
  401:
        body:
          application/json:
            example:
              {
                "message": "unauthorized"
              }
  403:
        body:
          application/json:
            example:
              {
                "message" : "Forbidden"
              }
  404:
        body:
          application/json:
            example:
              {
                "message" : "Not Found"
              }
  500:
    body:
      application/json:
        example:
          {
            "message" : "server error"
          }
      







