#%RAML 1.0 Extension
extends: craftolineshoping.raml
resourceTypes:
  collection: !include resource/adminresourceType.raml
/admin:
  get:
  post:
  put:
  delete: 

/Adminusers:
  get:
  
  type:
      collection:
        resourcePathName: users
        resourcePath: users                 
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }           
/Adminusers{userid}:
  get:
    
  type:
    collection:
      resourcePathName: usersid
      resourcePath: userid
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
/Adminproducts:
  get:
    
  type:
      collection:
        resourcePathName: products
        resourcePath: products 
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
/Adminproducts{id}:
  get:
    
  type:
      collection:
        resourcePathName: users{id}
        resourcePath: products{id}
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
/Adminorders:
  get:
    
  type:
      collection:
        resourcePathName: orders
        resourcePath: orders
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
   
/Adminorders{id}:
  get:
   
  type:
      collection:
        resourcePathName: orders{id}
        resourcePath: orders{id}
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
/Adminorders{uid}:
  get:
  type:
      collection:
        resourcePathName: orders{uid}
        resourcePath: orders{uid}
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
/Admicatagories:
  get:
   
  type:
    collection:
      resourcePathName: catagoties
      resourcePath: catagories
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }
/Admincatagories{id}:
  get:
  type:
      collection:
        resourcePathName: catagories{id}
        resourcePath: catagoryid
  post:
  put:
  delete:
    responses:
      200:
        body:
          application/json:
            example:
              {
              message: "resource deleted"
            }

