#%RAML 1.0 AnnotationTypeDeclaration
allowedTargets: [Methods]
properties:
  usage:
    description: use this annotations to understand details about oline shoping rest API
  controller:
    description: the user or the deveveloper have to be informed about the metadata
    properties:
      uri:
        description: dev.icraft.net is the uri which used to acess the rest api
        default: icraftsoft 
      protocol: 
       description: the rest api used HTTP protocol
       default: http
      visibility?:
        description: should the user or the developer need to know the url to the http method of the rest api
        type: boolean
        default: true
      MethoduSage?:
        description: 