#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/aa221b5d-b959-4b72-94f7-bc07af51fff8/ # 
title: crafto-line-shoping
version:
mediaType:
- application/json
protocols:
  - http
uses:
  mylib: library.raml
/users:
  description: this is the users resource
  get:
    queryParameters:
      id:
        description:  id
        type: integer
        required:  false
      fullName:
        description:  fname and lname
        type: string
        enum:
          [john, mike]
        required: false
      userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
      addres:
        default: john

    description: users resource get http tatus code responses
    responses:
      200:
        body:
          application/json:
            type: mylib.users
            example: !include Examples/users.json
  # type:
  #   collections:
  #     resourcepath: users
  is: 
  - mylib.responsemessage
  /{userid}:
    description: this is the userid resource
    get:
      queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [aregahegn, mekonenn]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: aregahegn
      responses:
       "200":
         body:
           application/json:
             example: !include Examples/userid.json
    type:
      mylib.collections:
        resourcepath: userid
    is: 
      mylib.responsemessage:         
  post:
    description: list of post status codes
    responses:
      200:
        body:
          application/json:
            example: !include Examples/Upost.json

    is: 
      mylib.responsemessage:
/products:
  description: find product resources
  get:
    queryParameters:
      id:
        description:  id
        type: integer
        required:  false
      fullName:
        description:  fname and lname
        type: string
        enum:
          [sami, geb]
        required: false
      userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
      addres:
        default: sami
    description: get all products
    responses:
      200:
        body:
          application/json:
            example: !include Examples/products.json 
  # type:
  #     collections:
  #       resourcepath: products         
  is:
    mylib.responsemessage:

  /products{id}:
    description: 
    get:
      queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [jedidiah, arege]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: edu
      responses:
        200:
          body:
            application/json:
              example: !include Examples/product.json
    type:
     mylib.collections:
       resourcepath: products{id}
               
    is: 
      mylib.responsemessage:
/orders:
  description: this is orders by id
  get:
    queryParameters:
      id:
        description:  id
        type: integer
        required:  false
      fullName:
        description:  fname and lname
        type: string
        enum:
          [john, mike]
        required: false
      userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
      addres:
        default: john
    description: find specific order
    responses:
      200:
        body:
          application/json:
            example: !include Examples/orders.json
  type:
      mylib.collections:
        resourcePathName: orders{id}
        resourcepath: orders{id}

  is: 
      mylib.responsemessage:        
/orders{uid}:
    description: get orders by user id
    get:
      queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [jedidiah, arege]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: edu
      description: find orders by users id
      responses:
        200:
          body:
            application/json:
              example: !include Examples/orderuser.json
    
    type:
      mylib.collections:
        resourcePathName: orders{uid}
        resourcepath: orders{id}         
    is: 
      mylib.responsemessage:
        
/orders{id}:
    description: get all orders
    get:
      queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [sami, geb]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: sami
      description: find all orders
      responses:
        200:
          body:
            application/json:
              example: !include Examples/order.json
    type:
      mylib.collections:
        resourcePathName: orders
        resourcepath: orders                
    is: 
      mylib.responsemessage:    
    post:
     description: post itemstes       
     responses:
      200:
        body:
          application/json:
            example: !include Examples/Opost.json
              
      201:
        body:
          application/json:
            example:
              {
                "message": "Created"
              }

     
     is: 
      mylib.responsemessage:
      
/catagories:
  description: 
  get:
    queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [jedidiah, arege]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: edu
    description: 
    responses:
      200:
        body:
          application/json:
            example: !include Examples/catagories.json
  type:
      mylib.collections:
        resourcePathName: catagories
        resourcepath: catagories          
  is: 
      mylib.responsemessage:
      
  /catagories{id}:
    description: 
    get:
      queryParameters:
       id:
        description:  id
        type: integer
        required:  false
       fullName:
        description:  fname and lname
        type: string
        enum:
          [sami, geb]
        required: false
       userName:
        description: username
        maxLength: 18
        minLength: 3
        required: false
       addres:
        default: sami
      description: 
      responses:
        200:
          body:
            application/json:
              example: !include Examples/catagory.json
                
    type:
      mylib.collections:
        resourcePathName: catagory id
        resourcepath: catagories{id}    
    is: 
      mylib.responsemessage:
        
          
              
            
              

                                        
              

      










  
    
