#%RAML 1.0 Library
usage: to define basic lib which used on this api raml specification
types:
  users: !include DataTypes/users.raml
traits:
  responsemessage: !include Traits/response.raml
  
resourceTypes:
  collections: !include resource/rootresourceType.raml
securitySchemes:
  oath: !include securityScheme.raml
# documentation:
#   - !include documentation.raml
annotationTypes:
  annotation: !include annotation.raml