#%RAML 1.0 NamedExample
products:
                {
                "categoryid": 3,
               "description": "string",
               "name": "string",
               "price": 125,
               "productid": 33,
               "video_url": "string"
              }