#%RAML 1.0 NamedExample
ordersID:
                 {
                "userid":"1000",
                "username":"nn22",
                "deleted":"false",
                "date":"25255"
                }